// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZZ05NwBoSsq7qEw1EftShmGoNkavIi80',
    appId: '1:212984130942:web:cfeee832c40c5a721e972f',
    messagingSenderId: '212984130942',
    projectId: 'carbonsync-flutter',
    authDomain: 'carbonsync-flutter.firebaseapp.com',
    storageBucket: 'carbonsync-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGi5kFQ_CMyqbdvs1S2vMs48gN0lzv1x8',
    appId: '1:212984130942:android:62bab825466d47a51e972f',
    messagingSenderId: '212984130942',
    projectId: 'carbonsync-flutter',
    storageBucket: 'carbonsync-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBReKqW5RwZjqirt_XfWe28ezOCpjYvRZs',
    appId: '1:212984130942:ios:d2522f1f1e92fffa1e972f',
    messagingSenderId: '212984130942',
    projectId: 'carbonsync-flutter',
    storageBucket: 'carbonsync-flutter.appspot.com',
    iosBundleId: 'com.example.carbonsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBReKqW5RwZjqirt_XfWe28ezOCpjYvRZs',
    appId: '1:212984130942:ios:d2522f1f1e92fffa1e972f',
    messagingSenderId: '212984130942',
    projectId: 'carbonsync-flutter',
    storageBucket: 'carbonsync-flutter.appspot.com',
    iosBundleId: 'com.example.carbonsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZZ05NwBoSsq7qEw1EftShmGoNkavIi80',
    appId: '1:212984130942:web:7b9adb1a051b6d741e972f',
    messagingSenderId: '212984130942',
    projectId: 'carbonsync-flutter',
    authDomain: 'carbonsync-flutter.firebaseapp.com',
    storageBucket: 'carbonsync-flutter.appspot.com',
  );
}
